### ISSUE TITLE
My app using ZSSRichTextEditor has been rejected on App Store.

### ISSUE THREAD

**Issue by lenlenlen** [nnhubbard/ZSSRichTextEditor#100]
Hi, Nic Hubbard.
Thank you for making a great code.

I want to one question.
Today, My app using ZSSRichTextEditor has been rejected by the App Store.

It was this message.
//////////////////////////////////////////////////////////////////
2.5 - Apps that use non-public APIs will be rejected
2.5 Details

Your app misuses UIWebBrowserView private class, which is a violation of the App Store Review Guidelines.

The use of non-public APIs is not permitted in the App Store because it can lead to a poor user experience should these APIs change.
/////////////////////////////////////////////////////////////////

Of course, I was used the latest ZSSRichTextEditor.
Perhaps,  I think that there is a problem here.
https://github.com/nnhubbard/ZSSRichTextEditor/blob/master/ZSSRichTextEditor/Source/ZSSRichTextEditor.m

I will continue to want to use this great code.
Please lend me strength.
Thank you for reading the message so far.

Regards,

**Comment by nnhubbard** [comment]
Did you get it approved?

**Comment by zhangzhang86** [comment]
Did you get it approved?

**Comment by YogendraPatel** [comment]
is apple still reject app if i use this library with "WKWebBrowserView" class?
