### ISSUE TITLE
TextEdit Area Flickers (May be scrolls up and then down)

### ISSUE THREAD

**Issue by coderrat** [nnhubbard/ZSSRichTextEditor#107]
I really appreciate your effort for this project. Its simply awesome.

I am just trying with demo apps Large option. Steps to reproduce flicker 

1. Select Large From List
2. Once screen school to bottom, press return key
3. Type anything, Screen Flicker
4. After this any return key and type same repeats

**Comment by william205** [comment]
@coderrat I have been unable to produce this on any simulator devices so I am going to close this issue, I will keep my out for this issue as I am developing though in case it reappears.
