### ISSUE TITLE
Pressing (Un)Ordered list, toolbar icon is not changing status

### ISSUE THREAD

**Issue by kostastsi** [nnhubbard/ZSSRichTextEditor#110]
While pressing the unordered or ordered list toolbar button, the action takes place correctly, but the toolbar is not updating its status (see enabledEditingItems). Please provide any advice or fix it.

**Comment by william205** [comment]
@kostastsi I have just tested this on all simulator devices and the unordered list button in the toolbar is changing status so I am going to close this issue for now. If you can provide clear steps on how to reproduce the issue again and I am able to reproduce it then I will re-open the issue.
