### ISSUE TITLE
how  to put ZSSRichTextEditor into my ViewController?

### ISSUE THREAD

**Issue by mylovetop** [nnhubbard/ZSSRichTextEditor#113]
how  to put ZSSRichTextEditor into my ViewController
i try this:
```
ZSSRichTextEditor *zssr = [[ZSSRichTextEditor alloc] init];
[zssr.view setTranslatesAutoresizingMaskIntoConstraints:NO];
[self.view addSubview: zssr.view];
```
but report error,
please help! thanks!

**Comment by nnhubbard** [comment]
You need to subclass `ZSSRichTextEditor` instead of adding it as a subview. See the examples provided.

**Comment by mylovetop** [comment]
my custom viewController must be inherit the ZSSRichTextEditor？ 
i want to add ZSSRichTextEditor into my custom viewController, how to do
thanks!

**Comment by nnhubbard** [comment]
Yes, it must inherit from `ZSSRichTextEditor`. It was design to completely take over as view controller, not be a subview.

**Comment by mylovetop** [comment]
i set my project the following：
`[self.navigationController setNavigationBarHidden:YES animated:NO];`
i custom the top of `NavigationBar`,  
how to do in the `ZSSRichTextEditor`  ?
my custom the top of `NavigationBar` can not cover the `ZSSRichTextEditor`  `s a part of content.
thanks!

**Comment by nnhubbard** [comment]
Not exactly sure what you mean...can you show a screenshot?

**Comment by mylovetop** [comment]
thanks! i solve it.
