### ISSUE TITLE
Can display images

### ISSUE THREAD

**Issue by Ewithome** [nnhubbard/ZSSRichTextEditor#116]
Images will display HTML.I tried not be displayed.Don't know there is no such.
Don't know there is no such function

**Comment by nnhubbard** [comment]
I am not really sure what you mean.

**Comment by Ewithome** [comment]
Will display pictures.  
![c264b12e-dd8e-47da-a5f3-8df42e1d66fc](https://cloud.githubusercontent.com/assets/8252464/16366544/72834f46-3c4b-11e6-8578-5c688fb3aa19.png)

**Comment by william205** [comment]
@Ewithome I have been unable to reproduce this issue so I am going to close it for now. If you can provide clear steps to reproduce this issue and I am able to reproduce it then I will re-open the issue.
