### ISSUE TITLE
Tool bar not visible

### ISSUE THREAD

**Issue by PraveenChellenkula** [nnhubbard/ZSSRichTextEditor#120]
Toolbar with control buttons are not visible as in attached screenshot. Do we have any known fixes please.

![simulator screen shot 21-apr-2016 3 59 34 pm](https://cloud.githubusercontent.com/assets/2841833/14705908/826f6b0c-07d9-11e6-841c-82f0841330ab.png)

**Comment by nnhubbard** [comment]
You are saying it isn't working with the demo project? What version of iOS?

**Comment by PraveenChellenkula** [comment]
Its working with demo project. But when I integrate in my project, toolbar is not coming (iOS 9.3).

**Comment by nnhubbard** [comment]
Then you must have done something different when integrating it into your project. Did you follow all of the instructions in the README?

**Comment by PraveenChellenkula** [comment]
Hi Hubbard, 
I integrated as per README file and same result in iPhone. But if I run in iPad toolbar options are coming. 
Any idea on what may be causing the issue in iPhone. 
Thanks for your help.

**Comment by PraveenChellenkula** [comment]
Hello Hubbard,
Issue was due to keyboard notifications not called due to silly mistake at my end. 
Sorry to bother you and once again thank you very much for your help.
