### ISSUE TITLE
Can this be used as just a UITextView?

### ISSUE THREAD

**Issue by halpz** [nnhubbard/ZSSRichTextEditor#121]
Can this be used as just a UITextView component dropped into an existing view controller and not a whole UIViewController of itself?

**Comment by nnhubbard** [comment]
No. `ZSSRichTextEditor` is a UIWebview which allows for the formatting of content, viewing of HTML, export of HTML, etc.

**Comment by halpz** [comment]
what i mean is can I use this component outside of the view controller? say if i wanted a UITextfield above the rich text editor?

**Comment by nnhubbard** [comment]
No, it currently only works as a viewController subclass.
