### ISSUE TITLE
App got rejected from AppStore..

### ISSUE THREAD

**Issue by Punith1234** [nnhubbard/ZSSRichTextEditor#128]
My app got rejected saying -- use of non - Publice Api's

**Comment by romanilchyshyn** [comment]
Probably because of #115.

**Comment by nnhubbard** [comment]
If someone is interested in working to fix this that is great, I just don't have time to address it right now.

**Comment by william205** [comment]
@Punith1234 I am going to close this issue because there is another open issue to do with this that I am currently working on a fix for.

**Comment by vaibhavsingla1996** [comment]
Does this issue of app not getting accepted at Appstore got fixed which was due to use of public api (i.e UIWebBrowserView )or not..?

**Comment by YogendraPatel** [comment]
is apple still reject app if i use this library with "WKWebBrowserView" class?
