### ISSUE TITLE
Mentions and hashtags support

### ISSUE THREAD

**Issue by Deliany** [nnhubbard/ZSSRichTextEditor#131]
Are you planning to support mentions and hashtags? I mean fire event when user start typing word starting `@` or `#` symbol or change caret position to such word and ability to replace(or insert) autocompleted mention or tag

**Comment by nnhubbard** [comment]
No, I really don't have time to work on this library right now. Feel free to submit a pull request!

**Comment by william205** [comment]
@Deliany I will work on adding a feature that fires an event when a word that starts with @ or # is typed.

**Comment by william205** [comment]
@Deliany I have added this feature, you can receive these events using the following methods in your subclassed ZSSRichTextEditor: 

    - (void)hashtagRecognizedWithWord:(NSString *)word {
    
        NSLog(@"Hashtag has been recognized: %@", word);
    
    }

    - (void)mentionRecognizedWithWord:(NSString *)word {
    
        NSLog(@"Mention has been recognized: %@", word);
    
    }
