### ISSUE TITLE
ZSSToolbarInsertImageFromDevice Custom Order Crash

### ISSUE THREAD

**Issue by william205** [nnhubbard/ZSSRichTextEditor#132]
When using a custom order with a select few bar button items, if I include ZSSToolbarInsertImageFromDevice I get a crash on:

self.toolbar.items = items; (line 715 in buildToolBar method)

Error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString view]: unrecognized selector sent to instance 0x100228460'

**Comment by purplepeng** [comment]
@william205 I have the same problem,what's your solution?Thanks.

**Comment by william205** [comment]
I managed to fix it by changing a line of code in the ZSSRichTextEditor.m source file.

Try going to the following method: 

- (NSArray *)itemsForToolbar

Then find

// Image From Device
    if ((_enabledToolbarItems && [_enabledToolbarItems containsObject:ZSSRichTextEditorToolbarInsertImageFromDevice]) || (_enabledToolbarItems && [_enabledToolbarItems containsObject:ZSSRichTextEditorToolbarAll])) {
        ZSSBarButtonItem *insertImageFromDevice = [[ZSSBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"ZSSimageDevice.png"] style:UIBarButtonItemStylePlain target:self action:@selector(insertImageFromDevice)];
        insertImageFromDevice.label = @"imageFromDevice";
        if (customOrder) {
            [items replaceObjectAtIndex:[_enabledToolbarItems indexOfObject:ZSSRichTextEditorToolbarInsertImage] withObject:insertImageFromDevice];
        } else {
            [items addObject:insertImageFromDevice];
        }
    }

I changed the following line:

[items replaceObjectAtIndex:[_enabledToolbarItems indexOfObject:ZSSRichTextEditorToolbarInsertImage] withObject:insertImageFromDevice];

to: 

[items replaceObjectAtIndex:[_enabledToolbarItems indexOfObject:ZSSRichTextEditorToolbarInsertImageFromDevice] withObject:insertImageFromDevice];

After I did that it all worked perfectly.

**Comment by nnhubbard** [comment]
Can you submit a PR for this?

**Comment by william205** [comment]
Pull request submitted

**Comment by nnhubbard** [comment]
Merged. Thanks!

**Comment by william205** [comment]
No problem

**Comment by purplepeng** [comment]
Thanks. 
There also have a small problem. The `ZSSimageDevice.png` image was not placed in the same path with others.
![sourceimage](https://cloud.githubusercontent.com/assets/3256113/18154030/d7375f38-7033-11e6-82c4-1c2f44eee3e0.png)

**Comment by william205** [comment]
I will submit a pull request for that to.
