### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xingze0308** [nnhubbard/ZSSRichTextEditor#136]
I use you zss_editor.removeFormating method  
not delete the format. 
How can I delete？

**Comment by xingze0308** [comment]
I use zss_editor.setBlockquote(); 
Now want to click on the button to get the reference style disappear
Could you please tell me how to get out of?

**Comment by xingze0308** [comment]
I have an issue with images not displaying, adding the first image is fine but then trying to add any more images just goes through the motions without displaying anything. Also updating images doesn't work.

**Comment by william205** [comment]
@xingze0308 I am going to close this issue because all of what you have said is either fixed or in other issues that have fixes in development.
