### ISSUE TITLE
How to remove the style of selected image border?

### ISSUE THREAD

**Issue by purplepeng** [nnhubbard/ZSSRichTextEditor#143]
Hi, i'm confused of how to remove the style of selected image border?In `ZSSRichTextEditor.js`or `ZSSRichTextEditor.m`? As the photo show below.
![db499f86-0ee2-4111-86ee-c2b9a03568b6](https://cloud.githubusercontent.com/assets/3256113/18440303/31fe4606-793b-11e6-85ba-d73dda5cb6bb.png). Thanks very much.

**Comment by william205** [comment]
@purplepeng to remove the border just delete the following style in the editor.html file.

    img.zs_active {
	    border: 2px dashed #000;
    }

You can't currently remove it from any of the other files or from a subclass of ZSSRichTextEditor however I am working on a custom css style feature which will enable this when it is complete.

**Comment by purplepeng** [comment]
It works. Thanks. @william205
