### ISSUE TITLE
App rejected when using ZSSRichTextEditor 

### ISSUE THREAD

**Issue by iksiphone** [nnhubbard/ZSSRichTextEditor#17]
Hi 
Apple rejects the app at the submission stage when ZSSRichTextEditor is included.
HRColorPicker is not included.

"The app contains or inherits from non-public classes in.... UIWebbrowserView"

Is anyone else face the same issue?

Patrick

**Comment by hammyhamza** [comment]
Is there any other workaround for this

**Comment by nnhubbard** [comment]
Did you get a rejection? If so, what did they say?

**Comment by hammyhamza** [comment]
Build uploaded to iTunes have an issue:

Non-public API usage:
The app contains or inherits from non-public classes in (App Name): UIWebBrowserView

**Comment by vaibhavsingla1996** [comment]
please tell me, will I be facing a rejection from apple fir using "UIWebBrowserView". If yes then what wil be the fix for this ?

**Comment by YogendraPatel** [comment]
is apple still reject app if i use this library with "WKWebBrowserView" class?
