### ISSUE TITLE
Crash when quickly enter and Change style 

### ISSUE THREAD

**Issue by vhbvb** [nnhubbard/ZSSRichTextEditor#172]
Thread 5 name:  WebThread
Thread 5 Crashed:
0   WebCore                       	0x000000018dab16c4 JSC::JSValue WebCore::wrap<WebCore::Range>(JSC::ExecState*, WebCore::JSDOMGlobalObject*, WebCore::Range&) + 212
1   WebCore                       	0x000000018d8ab888 WebCore::jsDOMSelectionPrototypeFunctionGetRangeAt(JSC::ExecState*) + 488
2   WebCore                       	0x000000018d8ab888 WebCore::jsDOMSelectionPrototypeFunctionGetRangeAt(JSC::ExecState*) + 488
3   JavaScriptCore                	0x000000018cc8b564 llint_entry + 28916
4   JavaScriptCore                	0x000000018cc8ab34 llint_entry + 26308
5   JavaScriptCore                	0x000000018cc8ab34 llint_entry + 26308
6   JavaScriptCore                	0x000000018cc8ab34 llint_entry + 26308
7   JavaScriptCore                	0x000000018cc8afd8 llint_entry + 27496
8   JavaScriptCore                	0x000000018cc842a8 vmEntryToJavaScript + 264
9   JavaScriptCore                	0x000000018cb6e5b8 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 164
10  JavaScriptCore                	0x000000018c4fafe8 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 416
11  JavaScriptCore                	0x000000018c807700 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) + 176
12  WebCore                       	0x000000018d258a40 
WebCore::JSEventListener::handleEvent(WebCore::ScriptExecutionContext*, WebCore::Event*) + 1068
13  WebCore                       	0x000000018d567478 WebCore::EventTarget::fireEventListeners(WebCore::Event&, WTF::Vector<WTF::RefPtr<WebCore::RegisteredEventListener>, 1ul, WTF::CrashOnOverflow, 16ul>) + 820
14  WebCore                       	0x000000018d566dec WebCore::EventTarget::fireEventListeners(WebCore::Event&) + 236
15  WebCore                       	0x000000018d55adf4 WebCore::EventContext::handleLocalEvents(WebCore::Event&) const + 116
16  WebCore                       	0x000000018d55be30 WebCore::EventDispatcher::dispatchEvent(WebCore::Node&, WebCore::Event&) + 796
17  WebCore                       	0x000000018d23433c WebCore::DocumentEventQueue::pendingEventTimerFired() + 240
18  WebCore                       	0x000000018d164acc WebCore::ThreadTimers::sharedTimerFiredInternal() + 172
19  WebCore                       	0x000000018d164a0c WebCore::timerFired(__CFRunLoopTimer*, void*) + 28
20  CoreFoundation                	0x0000000188599a9c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
21  CoreFoundation                	0x00000001885997a0 __CFRunLoopDoTimer + 856
22  CoreFoundation                	0x0000000188599060 __CFRunLoopDoTimers + 244
23  CoreFoundation                	0x0000000188596c84 __CFRunLoopRun + 1484
24  CoreFoundation                	0x00000001884c6d94 CFRunLoopRunSpecific + 424
25  WebCore                       	0x000000018d196b5c RunWebThread(void*) + 456
26  libsystem_pthread.dylib       	0x00000001876ad75c _pthread_body + 240
27  libsystem_pthread.dylib       	0x00000001876ad66c _pthread_body + 0
28  libsystem_pthread.dylib       	0x00000001876aad84 thread_start + 4

**Comment by vhbvb** [comment]
Crash appear When Input Chinese characters ... Crash message :EXC_BAD_ACCESS

**Comment by WildStrom** [comment]
这个问题解决了吗？我也碰到了。。
