### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by navisingh** [nnhubbard/ZSSRichTextEditor#22]
Thanks for this fantastic editor!  I have been playing with it and found that on iOS 8 beta 5, the keyboard behavior(show / hide) and the toolbar behavior (sliding) are buggy.  The keyboard hides but never comes back up, and the toolbar does not slide at all.

**Comment by rajinderpaul** [comment]
Yes. I am still facing the keyboard issue in iOS8, when pushing the viewController on iphone6 simulator.
