### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by DrashtiJaviya-Openxcell** [nnhubbard/ZSSRichTextEditor#240]
TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect

**Comment by MadeByDouglas** [comment]
So I am working on a PR to fix this on my own fork. https://github.com/MadeByDouglas/ZSSRichTextEditor In the process, the way to get JS Context has changed substantially. Does anyone have ideas how to apply this solution to ZSS ? https://stackoverflow.com/questions/25792131/how-to-get-jscontext-from-wkwebview

**Comment by nnhubbard** [comment]
The entire project needs to be updated to use `WKWebView` but sadly I do not have the time to do this.

**Comment by MadeByDouglas** [comment]
Right I understand, I am doing it. This is only missing component. It’s not the most elegant conversion but it should work.

**Comment by MadeByDouglas** [comment]
if anyone has ideas I posted the question here; I'm just not familiar with WebKit. https://stackoverflow.com/questions/58513792/how-do-i-repurpose-jscontext-in-uiwebview-to-wkscriptmessage-for-wkwebview

**Comment by MadeByDouglas** [comment]
I figured it out, PR is ready to solve this issue https://github.com/nnhubbard/ZSSRichTextEditor/pull/243
