### ISSUE TITLE
custom ZSSRichTextEditorToolbar not show..

### ISSUE THREAD

**Issue by huang5556019** [nnhubbard/ZSSRichTextEditor#25]
custom ZSSRichTextEditorToolbar when used ZSSRichTextEditorToolbarParagraph custom tools not show...

self.enabledToolbarItems = ZSSRichTextEditorToolbarSuperscript | ZSSRichTextEditorToolbarUnderline | ZSSRichTextEditorToolbarH1 | ZSSRichTextEditorToolbarH3 | ZSSRichTextEditorToolbarParagraph; 

the value is out of NSInteger  ; cause the value is negative..

**Comment by william205** [comment]
@nnhubbard did you fix this?

**Comment by nnhubbard** [comment]
Yes, see https://github.com/nnhubbard/ZSSRichTextEditor/blob/master/ZSSRichTextEditor/Source/ZSSRichTextEditor.h
