### ISSUE TITLE
Needs to remove references to UIWebView

### ISSUE THREAD

**Issue by halpz** [nnhubbard/ZSSRichTextEditor#267]
you can no longer submit apps that use UIWebView (from december) so this needs to be changed to WKWebView!

**Comment by nnhubbard** [comment]
`UIWebView` isn't used anymore. Have you made sure to update?

**Comment by codenameDuchess** [comment]
Hi @nnhubbard, when I pulled in the dependency with CocoaPods the other day it resolved to your last tagged release (with UIWebView). Any chance of y'all creating a new tagged release? (The pod spec references version 0.5.2.2 but there's no corresponding tag in this repo). Thanks in advance! 👍

**Comment by nnhubbard** [comment]
Just don't use CocoaPods. We haven't ever updated that.
