### ISSUE TITLE
ITMS-90809:

### ISSUE THREAD

**Issue by AllisonWangJiaoJiao** [nnhubbard/ZSSRichTextEditor#271]
ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by nnhubbard** [comment]
This project does does not use UIWebView. Please make sure you are using the latest version.

**Comment by AllisonWangJiaoJiao** [comment]
It has been updated to the latest version，thanks a lot.
