### ISSUE TITLE
does this lib under supported now?

### ISSUE THREAD

**Issue by fukemy** [nnhubbard/ZSSRichTextEditor#282]
Hi, does your library is still updating now?

**Comment by nnhubbard** [comment]
I do not currently have time to do updates on this project. Did you have a request?

**Comment by imashishbogati** [comment]
Hi @nnhubbard  is there any demo project in swift

**Comment by nnhubbard** [comment]
@imashishbogati No, this project was written in Objective-C. Feel free to submit a pull request for any changes.
