### ISSUE TITLE
The editor is not scrolling when creating a hidden new line

### ISSUE THREAD

**Issue by kurotsukikaitou** [nnhubbard/ZSSRichTextEditor#36]
Like the tittle said, the editor (I don't know which class is the html editor is) doesn't get scrolled when user create new line on the bottom of the visible area. The caret just looks like goes below the visible area without any scrolling to make the new position of the caret visible. For better picture, see the attached screenshot.
![ios simulator screen shot sep 12 2014 5 57 02 pm](https://cloud.githubusercontent.com/assets/5329246/4248885/1c1e5358-3a6d-11e4-9fbe-9e543c36fed2.png)

**Comment by parthpatel1105** [comment]
I got same issue after add image and start to write text very near by image. Can you give proper solution?

**Comment by william205** [comment]
@kurotsukikaitou I believe that this has been fixed because I replicated your screenshot and had no issues with it, can you confirm if it has been fixed or not please? 

@parthpatel1105 please can you also confirm if your issue is still present or not when using the latest version of the source?

**Comment by william205** [comment]
I am going to close this issue for now, but if anyone still has issues with this then comment and I will re-open the issue. @parthpatel1105 @kurotsukikaitou
