### ISSUE TITLE
Not able to insert link

### ISSUE THREAD

**Issue by ankitgupta1309** [nnhubbard/ZSSRichTextEditor#38]
I am entering the "url" and the ''title'', but it does not show up. I checked it is going inside the functions as told, but nothing comes up on screen. Help required asap. 
Thanks

**Comment by abhishekgoyal12** [comment]
Use this code and it will insert the link without selecting any text

zss_editor.restorerange();
    var html_code = '<a href="' + url + '">' + title + '</a>';
    zss_editor.insertHTML(html_code);
