### ISSUE TITLE
getText method does not seem to get all text.

### ISSUE THREAD

**Issue by nnhubbard** [nnhubbard/ZSSRichTextEditor#41]
Comment from a user:

1. During a selection of text, when I tap at "B"(bold) or any other functions, it doesn't apply the css to the selected text. It does work when you tap "B" first and start typing though, the css does apply.

2. When I am done, I try to use [self getText] to extract the text. But the text doesn't look great as there's no "space" in between the texts. You can see the effect from my attachment.

3. I use [self getHTML] and [self getText] and set into a core data object. When I go back into edit mode and setting the html text using [self setHTML:htmlText]. The text appear as expected. But upon that, making a call to [self getText] only return partial text, as you can see from the attachment. First attempt was "RolandPray for healthPray for ti...", but the second attempt only gives me "Roland".

**Comment by william205** [comment]
I am assuming these issues have been fixed because I have just tested all of them and the issues do not happen. I will close the issue.
