### ISSUE TITLE
insertImage:alt: does not seem to work

### ISSUE THREAD

**Issue by nnhubbard** [nnhubbard/ZSSRichTextEditor#52]
Seems there is an issue with this method not working. Although the insert image button does work.

**Comment by changcode** [comment]
insertImage:alt:  button did working, but after insert it doesn't appear on the view. It just show blue question mark,

**Comment by nnhubbard** [comment]
What code did it insert? Did you use an absolute URL?

**Comment by changcode** [comment]
I found the reason, on iOS 9 we need to set on plist
 <key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

**Comment by beydeng** [comment]
user insertImage:alt can't work
the url looks like  http://.../img/topic/20181218/15451297703346imageSize=W=40H=150.jpeg
how can i fix it?
