### ISSUE TITLE
Using hardware keyboard should show toolbar at bottom of screen

### ISSUE THREAD

**Issue by nnhubbard** [nnhubbard/ZSSRichTextEditor#58]
When connecting a hardware keyboard, there currently isn't any way to edit the HTML. The toolbar needs to stick to the bottom of the screen.

**Comment by william205** [comment]
I believe I have created a fix for this issue, I will push it later this evening a long with a few other fixes. I have created a property called `alwaysShowToolbar` which when set to YES should keep the toolbar visible when a hardware keyboard is connected.
