### ISSUE TITLE
updateHTML sometimes not success 

### ISSUE THREAD

**Issue by huang5556019** [nnhubbard/ZSSRichTextEditor#63]
I test found when html source include "'" need replace to "&#39;" 
like this:
- (NSString *)removeQuotesFromHTML:(NSString *)html {
  html = [html stringByReplacingOccurrencesOfString:@"\"" withString:@"\\""];
  html = [html stringByReplacingOccurrencesOfString:@"“" withString:@"&quot;"];
  html = [html stringByReplacingOccurrencesOfString:@"”" withString:@"&quot;"];
  html = [html stringByReplacingOccurrencesOfString:@"'" withString:@"&#39;"];
  html = [html stringByReplacingOccurrencesOfString:@"\r"  withString:@"\r"];
  html = [html stringByReplacingOccurrencesOfString:@"\n"  withString:@"\n"];
  return html;
  }
  to fix the problem

**Comment by AllisonWangJiaoJiao** [comment]
You can try this method.

- (void)updateHTML {
    
    NSString *html = self.internalHTML;
     NSAttributedString *htmlAtt = [[NSAttributedString alloc] initWithString:html];
     self.sourceView.attributedText = htmlAtt;
     NSString *cleanedHTML = [self removeQuotesFromHTML:html];
     NSString *trigger = [NSString stringWithFormat:@"zss_editor.setHTML(\"%@\");", cleanedHTML];
     [self.editorView evaluateJavaScript:trigger completionHandler:^(NSString *result, NSError *error) {
     }];
     // 计算个数
    __block NSString * textCountString;
    [self.editorView evaluateJavaScript:@"zss_editor.getText();" completionHandler:^(NSString *result, NSError *error) {
        textCountString = [textCountString stringByReplacingOccurrencesOfString:@" " withString:@""];
          textCountString = [textCountString stringByReplacingOccurrencesOfString:@"　" withString:@""];
          textCountString = [textCountString stringByReplacingOccurrencesOfString:@" " withString:@""];
          textCountString = [textCountString stringByReplacingOccurrencesOfString:@"*{word-break:break-all;}" withString:@""];
          textCountString = [textCountString stringByReplacingOccurrencesOfString:@"*{box-sizing:border-box;}" withString:@""];
          NSInteger num = textCountString.length;
        self->_rightItem.text =[NSString stringWithFormat:@"%zd字",num];
    }];
  
}
