### ISSUE TITLE
Represent Formatting at Cursor via Toolbar Item Color

### ISSUE THREAD

**Issue by fabb** [nnhubbard/ZSSRichTextEditor#69]
In the readme image, the formatting toolbar items represent active formattings, e.g. when a selection is bold, the toolbar button becomes black:

https://camo.githubusercontent.com/3f9c01eba9c69d030a69faaa1a2e01a733244627/687474703a2f2f636c2e6c792f696d6167652f3369343134303367323030422f64656d6f2e676966

![image](https://cloud.githubusercontent.com/assets/153960/5198879/ce648bda-7556-11e4-9b41-e10977742890.png)

This seems not to work in the current version on the master branch. Was this feature dropped? Will it come back?

**Comment by william205** [comment]
I believe that this issue has been fixed as it is working with the latest source so I am going to close this issue.
