### ISSUE TITLE
0.5.2.1: The Keyboard Appears, Disappears and Appears Again

### ISSUE THREAD

**Issue by fabb** [nnhubbard/ZSSRichTextEditor#70]
Reproduction Steps:

* Start the example project on iOS 8 iPhone 6 and open the "Large" example
* Dismiss the keyboard
* Tap into the text area
* => The keyboard appears, and disappears again immediately. Sometimes it appears again afterwards

This behavior is new since 0.5.2.1

**Comment by eikebartels** [comment]
Any news about this issue?

**Comment by nnhubbard** [comment]
Have not even had a chance to look into this. If you have a chance to look into it, that would be great!

**Comment by eikebartels** [comment]
Do you know where about? I can't find any firstResponder inside the hole project

**Comment by nnhubbard** [comment]
Pretty sure it is a javascript issue as I remember this being a problem in the past.

**Comment by westice007** [comment]
I also meet this problem, Who has the solution？

**Comment by D-32** [comment]
Any updates on this?

**Comment by nnhubbard** [comment]
Nope, none yet. No time to even check into it. Really looking for some extra help on this project..

**Comment by D-32** [comment]
Yeah, I know that.
When removing `zss_editor.enabledEditingItems(e);`on line 42 inside the js file it seems to work. Not exactly sure why we're calling this function here. Do you know why that should be needed there?

**Comment by LJJ** [comment]
Probably I figured out this problem. 
$(window).on('touchend', function(e) {
                 if (!zss_editor.isDragging) {
                 zss_editor.focusEditor();
                 }
                 });
focusEditor ensures we move the cursor to the end of the editor, somehow it will disturb selection when you tap text area at first time

**Comment by nnhubbard** [comment]
@LJJ Are you able to test the fix and submit a pull request?

**Comment by william205** [comment]
I believe that this issue has been fixed as I followed @fabb's reproduction steps and wasn't able to reproduce the issue on any of the simulator devices using iOS 8 or iOS 9. I will close this issue.
