### ISSUE TITLE
Insert links

### ISSUE THREAD

**Issue by michalciolek** [nnhubbard/ZSSRichTextEditor#80]
When user trying insert links without selecting text, the links don't appear... 
I thing library should insert URL or title into `<a>` tag (e.g. `<a href="URL">URL or title</a>`)and inserts it into editor.

**Comment by pang0018** [comment]
~michalciolek

I ran into the same issue. I modified the zss_editor.insertLink function in ZSSRichTextEditor.js to be

zss_editor.insertLink = function(url, title) {
    zss_editor.restorerange();
    var html_code = '<a href="' + url + '">' + title + '</a>';
    zss_editor.insertHTML(html_code);
}

Use at own risk!

**Comment by nnhubbard** [comment]
@pang0018 - Really not sure how that code would help.

**Comment by pang0018** [comment]
Well link inserting was not working on my device when I cloned your project. If there is something better I am all ears!

**Comment by nnhubbard** [comment]
Inserting links works correctly. What issues are having?

**Comment by pang0018** [comment]
I don't recall, It was over 3 months ago. We ended up not using the link insertion part so it didn't matter. When we decide to use that I will post what issues I am having, if any.

**Comment by szl-926929** [comment]
I have the same question!!

**Comment by szl-926929** [comment]
insert links without selecting text，i get next content:
<p>This is a test of the <strong>ZSSRichTextEditor</strong> by <a title="Zed Said" href="http://www.zedsaid.com">Zed Said Studio</a>
</p>
<p>
    <br />
</p>

**Comment by william205** [comment]
I have just tested the links and they are working properly, I can not reproduce the issue you are encountering so for now I will close this issue. @szl-926929 @pang0018 @michalciolek if you can produce the exact steps you did when you came across this issue and I can reproduce the issue from those steps then I will re-open this issue.
