### ISSUE TITLE
inputView

### ISSUE THREAD

**Issue by tinhbka** [nnhubbard/ZSSRichTextEditor#85]
your source is very cool, but now how to custom inputView for keyboard of editor (webview). please suggest me. tks so much!

**Comment by nnhubbard** [comment]
Not exactly sure what you mean...

**Comment by tinhbka** [comment]
i want to custom input view for webview, like emoji keyboard, so suggest me how to set inputView for uiwebview tks

**Comment by nnhubbard** [comment]
There isn't a supported way to set the inputView for a webView. We had to do it a different way.
