### ISSUE TITLE
Remove format option not working 

### ISSUE THREAD

**Issue by BluePick** [nnhubbard/ZSSRichTextEditor#88]
- (void)removeFormat {
    NSString *trigger = @"zss_editor.removeFormating();";

    [self.editorView stringByEvaluatingJavaScriptFromString:trigger];
}

not removing any formating..... ;(

**Comment by nnhubbard** [comment]
It does work. I just tested it in the demo project.

What is not working for you? It will remove formatting, e.g. bold, italic, etc. Not links.

**Comment by william205** [comment]
@BluePick I have just tested the remove format method and it works as it should. I will mark this issue as closed for the moment but if you explain in detail the issues you are having with it and let me know steps to reproduce the issue and I am able to reproduce it then I will re-open it.
