### ISSUE TITLE
Convert html to plaintext

### ISSUE THREAD

**Issue by luvcjssy** [nnhubbard/ZSSRichTextEditor#90]
When I copy a paragraph from other website. That html text contain style css inside html tag (Ex: <div style="color:red">Test</div>). How I can convert that text to plaintext (Ex: Test)

**Comment by nnhubbard** [comment]
That is pretty much how all WYSIWYG editors work. They bring in the styles of their copied source. This isn't something that we are interested in taking the time to support.

As an alternative you could paste the content into the Source editor.
