### ISSUE TITLE
placeholder not working?

### ISSUE THREAD

**Issue by stanleyfok** [nnhubbard/ZSSRichTextEditor#92]
seems cannot set placeholder?

**Comment by Milan3792** [comment]
Hey stanleyfok,
Did you find anything for adding placeholder?

**Comment by hagile** [comment]
+1

**Comment by dickhahn** [comment]
<body onLoad="zss_editor.init();">
      <div id="zss_editor_content" style="width: 100%; height: 100%; -webkit-overflow-scrolling: touch; overflow: auto;" contenteditable="true" placeholder="Type something..."></div>
      <div id="zss_editor_footer"> </div>
  </body>

**Comment by dickhahn** [comment]
in editor.html

	<div id="zss_editor_content" style="width: 100%; height: 100%; -webkit-overflow-scrolling: touch; overflow: auto;" contenteditable="true" placeholder="Type something..."></div>
	<div id="zss_editor_footer"> </div>


add "placeholder" property to zss_editor_content div and set it value what u want,then use css to control it(for example:#zss_editor_content:empty:before{content: attr(placeholder);color:#bbb;}#zss_editor_content:focus:before{content:none;})

Sadly, this is an ugly way :(

**Comment by william205** [comment]
I will add getting the placeholder feature working to my list of things to do.

**Comment by william205** [comment]
Placeholder is now working, you can set it using `setPlaceholder`.

    [self setPlaceholder:@"placeholder text"];
