### ISSUE TITLE
not select text，insert link not work， input，the view always  shake

### ISSUE THREAD

**Issue by szl-926929** [nnhubbard/ZSSRichTextEditor#95]

**Comment by nnhubbard** [comment]
Not really sure what you mean...

**Comment by szl-926929** [comment]
if i insert a link。APP show a alter view。i input url and Title.but,it do not work. and if i insert an image. then, i input text, the input view shake  everytime when i insert text.
my english is pool. i'm sorry .
That are related to the project implementation notes? So, I can easily understand and modify the source code

**Comment by william205** [comment]
@szl-926929 I have been unable to recreate this issue so I am going to mark it as closed for the moment but if you can provide some clear steps to reproduce the issue and I am able to reproduce it then I will re-open it.
