### ISSUE TITLE
Keyboard not showing under iOS 9

### ISSUE THREAD

**Issue by neowinston** [nnhubbard/ZSSRichTextEditor#98]
It shows fine under iOS 7 to 8, by using:

 **self.editorView.keyboardDisplayRequiresUserAction = NO;** 

But it's not working on iOS 9. 

Is there a fix for this?

Thanks!

**Comment by hagile** [comment]
Have you able to fix it?

**Comment by neowinston** [comment]
Yes, I fixed it. But I can't remember what I did. I'm trying to figure it out.

**Comment by hagile** [comment]
@neowinston, please do let me know if you found the solution :+1:

**Comment by neowinston** [comment]
Sure, I'm on it.

**Comment by neowinston** [comment]
Sorry, couldn't find my fix now, but I assure you that it's woking under iOS 7, 8 and 9. Can try again later.

**Comment by masong2012** [comment]
1) Keyboard will Disappear when TextEditor has many newline,and I can't Edit it any more
2)It locate the last row in Editor frequently, however i finger locate in.
Some people encountered such a problem?

**Comment by william205** [comment]
@neowinston @hagile @masong2012 I have just tried to recreate this issue and I wasn't able to so I am going to close this issue for now but if you can give me some clear steps to reproduce this issue and I am able to reproduce it then I will re-open it.
