### ISSUE TITLE
ERROR ITMS-90060: The value for the key CFBundleShortVersionString ‘0.5.2.1’ in the info.plist file must be a period-separated list of at most three non-negative integers

### ISSUE THREAD

**Issue by michaelloistl** [nnhubbard/ZSSRichTextEditor#99]
<img width="590" alt="submission error" src="https://cloud.githubusercontent.com/assets/1968209/10799961/7da9a16c-7da7-11e5-840e-f7b9b6085ae2.png">

**Comment by nnhubbard** [comment]
This should have nothing to do with `ZSSRichTextEditor`.

**Comment by michaelloistl** [comment]
ZSSRichTextEditor's info.plist would be the only one in my project that has the version ```0.5.2.1```. I would also have thought that this shouldn't have any impact but it looks like there have been some changes in the submission process. Once I remove ```ZSSRichTextEditor``` from my project I can submit without any issues. So it's most likely that this issue is related to ```ZSSRichTextEditor```'s version number.

**Comment by nnhubbard** [comment]
Why are you including the example project `info.plist` file in your project? You can just manually change the version number to match your app's version number.

**Comment by michaelloistl** [comment]
Not including the example project. Just using the cocoapod and the info.plist gets created with the pod. The invalid version number is part of your podspecs  ```s.version = "0.5.2.1"```

**Comment by codwam** [comment]
It should be changed to another version while I use cocoapods has the same problem.
@nnhubbard
